let str1 = 'This is a string';
let str2 = "This is a different string";
let str3 = `This is another string`;
let str4 = "true";
let str5 = "65968.54";
let str6 = 'false';
let str7 = '!@##$%&(*';
let userName = "SinaSasani";
let message = "hi there i'm Sina Sasani. i live in \"Tokyo\" in js Streat";
let welMsg = `"Hello ${userName} welcome to our website`;
console.log(message);
console.log(welMsg);
// console.log(typeof str1);
// console.log(typeof str2);
// console.log(typeof str3);
// console.log(typeof str4);
// console.log(typeof str5);
// console.log(typeof str6);
// console.log(typeof str7);